### ISSUE TITLE
Don't unmount inactive routes

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-drawer#4]
Instead just do what tab navigators do.

Migrated issue from https://github.com/react-navigation/react-navigation/issues/2277

**Comment by Li357** [comment]
Is there any way to add handlers for willBlur, didFocus, etc. instead of unmounting? All my images reload in the drawer and my components get remounted causing a lot of bad UX.

**Comment by Li357** [comment]
I created a temporary hack [on my fork](https://github.com/Li357/react-navigation-drawer) that mimics react-navigation-tabs' behavior with tabs. It seems to work fine on my demo, but is it good to copy ResourceSavingScene?

**Comment by felixgourdeau** [comment]
Any ETA when this issue will be closed? Thanks

**Comment by brentvatne** [comment]
no

**Comment by duhseekoh** [comment]
fyi, the current 'solutions' of nesting a stack immediately beneath a drawer and then putting all of the drawer screens into that stack has several flaws.

1. Fixable - transitions aren't right, the drawer screens slide in. can adjust transition in stack settings.
2. Fixable - there's a header that has to be turned off. can set headerMode = none.
3. Not fixable - determining which drawer item is active since activeItemKey passed to the drawer component always points to that child stack of the drawer. would need to somehow figure out for every route in your app which corresponds to which drawer screen 👎

**Comment by jaltin** [comment]
Hi @brentvatne,

I had to switch over to wix react-native-navigation a while back because of this specific problem with drawer navigators. I would love to switch back to react-navigation again, and I was wondering if you have any idea of when this might get some TLC?

Many thanks!

**Comment by satya164** [comment]
PR welcome :)

**Comment by jaltin** [comment]
Touche! :) 

I totally appreciate all the work that many people put into this. Unfortunately I'm not comfortable/skilled enough to fix such a thing. Hopefully one day I might be able to chip in.

**Comment by brentvatne** [comment]
@jaltin - I'm planning on working on it in this week

**Comment by jaltin** [comment]
Fantastic to hear @brentvatne! Thanks so much for looking at it!

**Comment by jaltin** [comment]
@brentvatne - Did you start work on this? Im curious to know if you have any guesstimate on when/if this might be fixed.

**Comment by brentvatne** [comment]
yes it's done already if you use react-navigation@3.0.0-rc

**Comment by brentvatne** [comment]
related commit: https://github.com/react-navigation/react-navigation-drawer/commit/fdb56a5df534d1715fe30c36818ea7cb225f9946

**Comment by jaltin** [comment]
That's fantastic news @brentvatne! Thanks a lot for your hard work!

**Comment by jaltin** [comment]
@brentvatne, I just wanted to let you know that I have now converted my app to use react-navigation 3 and the fixes you made works perfectly - thanks!

**Comment by brentvatne** [comment]
great to hear!
