### ISSUE TITLE
Handle back button when drawer is open

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-drawer#9]

**Comment by Dror-Bar** [comment]
Thank you Brentvatne.
I've noticed this issue is also related to [this one](https://github.com/react-navigation/react-navigation-drawer/issues/11).

My question is, and I know it might be difficult to answer, but do you have a rough estimation on when might this be fixed?
I'm working on a project right now, and If it could take more than a month, I'd need to go with an older version of this library that I know works for sure.
Thank you.

**Comment by brentvatne** [comment]
no estimate

**Comment by Dror-Bar** [comment]
@brentvatne Could you perhaps hint at how I could achieve this? I don't mind altering the library in the meantime if I need to - I'm just not sure what change made this happen (I assume it started with version 2.0 but not sure).


I tried overwriting the back button handler, but it's no good since the bug makes it so isDrawerOpen is undefined - no way to tell if it's actually open or closed.


Regardless thank you for the feedback.

**Comment by Dror-Bar** [comment]
Fixed in latest version! (currently 2.11.2).

Thank you very much. This can be closed.

**Comment by eriveltonelias** [comment]
I just tested it on `react-navigation@3.5.1` and is working perfectly. :)

https://snack.expo.io/@eriveltonelias/handle-back-button-when-drawer-is-open
